In [ ]:
import numpy as np # NP YAZAN YERE KÜTÜHANENİN TAKMA ADI (BENİM KOYDUĞUM AD)

In [ ]:
a = np.array([1,2,3])

In [ ]:
print(a)

[1 2 3]

In [ ]:
dizi = np.array([1,2,3,5.23])
print(dizi)

[1.   2.   3.   5.23]

In [ ]:
dizi1 = np.array([1,2,3,5.93],dtype=int) # DTYPE=İNT SADECE İNT OLARAK VERİYOR
print(dizi1)

[1 2 3 5]

In [ ]:
boyut1 = np.array([1,2,3]) # TEK BOYUTLU

In [ ]:
boyut2 = np.array([[1,2,3],[4,5,6]]) # ÇİFT BOYUTLU

In [ ]:
boyut3 = np.array([[[1,2,3],[4,5,6]] , [[7,8,9],[10,11,12]]]) # ÜÇ BOYUTLU

In [ ]:
print(boyut1)
print("---------------")
print(boyut2)
print("---------------")
print(boyut3)
print("---------------")

[1 2 3]
---------------
[[1 2 3]
 [4 5 6]]
---------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
---------------

In [ ]:
dizistring = np.array(["Safranbolu" , "Karabük"])
print(dizistring)

['Safranbolu' 'Karabük']

In [ ]:
sDizi1 = np.zeros(5)
print(sDizi1)

[0. 0. 0. 0. 0.]

In [ ]:
sDizi12 = np.zeros(5, dtype=int)
print(sDizi12)

[0 0 0 0 0]

In [ ]:
sDizi2 = np.ones(5)
print(sDizi2)

[1. 1. 1. 1. 1.]

In [ ]:
sDizi3 = np.full((3,4),10)
print(sDizi3)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

In [ ]:
aDizi = np.arange(1,30,2)
print(aDizi)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]

In [ ]:
lDizi = np.linspace(0,10,num=5) # 0'DAN 10'A KADAR 5 PARÇAYA BÖL
print(lDizi)

[ 0.   2.5  5.   7.5 10. ]

SINAVDA KESİN ÇIKAR - CUMHUR HOCA
### **RANDOM.RANDİNT**

In [ ]:
rDizi = np.random.randint(0,10,5) # SINAVDA KESİN ÇIKAR
print(rDizi) # 0-10 ARASINDA 5 BASAMAKLI SAYILARLA RANDOM OLUŞTUR 10'DAHİL DEĞİL

[8 7 9 3 7]

In [ ]:
rDizi1 = np.random.randint(0,10,(3,4)) # SINAVDA KESİN ÇIKAR
print(rDizi1)# 0-10 ARASINDA 4 BASAMAKLI 2 BOYUTLU SAYILARLA RANDOM OLUŞTUR 10'DAHİL DEĞİL

[[6 6 0 3]
 [0 5 7 0]
 [9 4 0 8]]

In [ ]:
hocaörnekDizi = np.random.randint(20,36,(5,6))
print(hocaörnekDizi)

[[26 27 32 23 22 22]
 [30 23 27 34 33 29]
 [22 20 23 28 27 31]
 [20 27 33 29 32 30]
 [27 27 21 23 23 33]]

SINAVDA KESİN ÇIKAR - CUMHUR HOCA
.SHAPE
.NDİM
.SİZE

In [ ]:
print(rDizi1.shape) # dizinin satır sütün sayısını verir

(3, 4)

In [ ]:
print(rDizi1.ndim) # dizinin boytunu verir

2

In [ ]:
print(rDizi1.size) # dizinin eleman sayısı

12

In [ ]:
boyut1 = np.array([1,2,3]) # TEK BOYUTLU
boyut2 = np.array([[1,2,3],[4,5,6]]) # ÇİFT BOYUTLU
boyut3 = np.array([[[1,2,3],[4,5,6]] , [[7,8,9],[10,11,12]]]) # ÜÇ BOYUTLU

DİZİLERDE BEN BAŞTAKİ SAYI 0 OLUR 1 OLMAZ

In [ ]:
print(boyut1[2]) # tek boyutlu dizinin istediğimiz elemanına ulaşma

3

In [ ]:
print(boyut2[0,1]) # 2 boyutlu dizinin istediğimiz elemanına ulaşma

2

In [ ]:
boyut2[1,2] = 10 # 2 boyutlu dizinin istediğimiz elemnanına ulaşma ve değerini değiştirme

In [ ]:
print(boyut3[1,0,2])

9

In [ ]:
boyut3[1,0,2] = 10 # 3 boyutlu dizinin istediğimzi elemanına ulaşma ve değerini edeğiştirme

In [ ]:
print(boyut1)
print("---------------")
print(boyut2)
print("---------------")
print(boyut3)
print("---------------")

[1 2 3]
---------------
[[ 1  2  3]
 [ 4  5 10]]
---------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8 10]
  [10 11 12]]]
---------------

In [ ]:
a = np.arange(10,20) # PRİNT(A) YERİNE DİREK A YAZIPTA PRİNT ATILABİLİR
print(a)

[10 11 12 13 14 15 16 17 18 19]

In [ ]:
a[0:4] # 0'DAN BAŞLAYIP 4. SAYIYA KADAR GİT 4 DAHİL DEĞİL

array([10, 11, 12, 13])

In [ ]:
a[:4] # 0'DAN BAŞLAYIP 4. SAYIYA KADAR GİT 4 DAHİL DEĞİL

array([10, 11, 12, 13])

In [ ]:
a[4:] # 4'DEN BAŞLAYIP SONA GİT

array([14, 15, 16, 17, 18, 19])

In [ ]:
a[::3] # 0'DAN BAŞLAYIP 3'ER 3'ER İLERLE

array([10, 13, 16, 19])

In [ ]:
a[-1] # SONDAN BİRİNCİ ELEMANI VERİR

19

In [ ]:
a[-6:8] # SONDAN 6. SAYI : 6.SAYIDAN 8.SAYIYA KADAR GİT **8.SAYI DAHİL DEĞİL**

array([14, 15, 16, 17])

In [ ]:
y = np.random.randint(0,40,(6,8))
y

array([[39,  4, 13, 34, 29, 34, 26, 26],
       [10, 20, 29, 20, 34, 32,  2, 28],
       [17, 13, 23,  0,  9, 25, 16, 24],
       [17, 20,  1,  2, 11, 10, 12, 22],
       [35, 25, 20,  8, 35,  6, 30, 13],
       [34,  7, 30, 17, 18, 25, 27, 28]])

In [ ]:
y[2,:] # 3.SATIRDAKİ HERŞEYİ AL

array([17, 13, 23,  0,  9, 25, 16, 24])

In [ ]:
y[2,4:7] # 3.SATIRDAKİ 4 İLE 7.SAYILARI VERİR 7 DAHİL DEĞİL

array([ 9, 25, 16])

In [ ]:
y[:,3:5] # 3.SÜTÜN İLE 5.SÜTÜN ARASINDAKİLERİNİ ATAR 5 DAHİL DEĞİL

array([[34, 29],
       [20, 34],
       [ 0,  9],
       [ 2, 11],
       [ 8, 35],
       [17, 18]])

In [ ]:
y[y<30] # Y NİN İÇİNDEKİ 30'DAN KÜÇÜK OLAN ELEMANLARI VERİR

array([ 4, 13, 29, 26, 26, 10, 20, 29, 20,  2, 28, 17, 13, 23,  0,  9, 25,
       16, 24, 17, 20,  1,  2, 11, 10, 12, 22, 25, 20,  8,  6, 13,  7, 17,
       18, 25, 27, 28])

In [ ]:
x = np.arange(10,30)

In [ ]:
x[0:4]

array([10, 11, 12, 13])

In [ ]:
x[:4]

array([10, 11, 12, 13])

In [ ]:
x[4:]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
x[0:10:2]

array([10, 12, 14, 16, 18])

In [ ]:
z = np.random.randint(0,10,(4,4))
z

array([[9, 6, 8, 9],
       [8, 4, 1, 6],
       [5, 2, 9, 0],
       [6, 9, 5, 5]])

In [ ]:
z[1,:]

array([4, 4, 0, 7])

In [ ]:
z[:,1]

array([0, 4, 5, 7])

In [ ]:
z[0:2,0:3]

array([[9, 6, 8],
       [8, 4, 1]])

In [ ]:
z[:,0:2]

array([[5, 0],
       [4, 4],
       [8, 5],
       [7, 7]])

In [ ]:
z[z>4]

array([5, 7, 7, 8, 5, 5, 7, 7, 6, 8])

In [ ]:
c = np.array([[10,20,30,40,65],[50,60,70,90,95], [15,25,35,55,5]])
c

array([[10, 20, 30, 40, 65],
       [50, 60, 70, 90, 95],
       [15, 25, 35, 55,  5]])

In [ ]:
b = np.random.randint(10,101,(3,5))
b

array([[ 50,  18, 100,  77,  41],
       [ 25,  93,  72,  65,  15],
       [ 18,  20,  69,  13,  72]])

In [ ]:
print(b.size)

15

In [ ]:
b[:,1:2]
print(b[:,3:4])

[[50]
 [43]
 [11]]

In [ ]:
b[b>50]

array([98, 76, 89, 51, 89, 60, 73])

*Soru ve cevapları*
1-C
2-A
3-D
4-

In [ ]:
a = np.array([ 2, 4, 6, 8 ])
a**2

array([ 4, 16, 36, 64])

In [ ]:
b = np.arange(1,7)
b

array([1, 2, 3, 4, 5, 6])

In [ ]:
c = np.array([3.14, 4,6,1.2])
c

array([3.14, 4.  , 6.  , 1.2 ])

In [ ]:
a = np.array([[4, 7, 4, 5, 9], [2, 5, 0, 7, 7], [1, 9, 0, 8, 2]])
a[:2,:3]

array([[4, 7, 4],
       [2, 5, 0]])

In [ ]:
v = np.array([0,3,6,9,12,15,18,21,24,27])
v = v[1],v[3]
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
np.power(v,3)

array([ 27, 729])

In [ ]:
print(v**3)

[    0    27   216   729  1728  3375  5832  9261 13824 19683]

In [ ]:
o = np.array([3.14,4,6,1.2])
o

array([3.14, 4.  , 6.  , 1.2 ])

In [ ]:
t = 5*np.array([1,2,3])
t

array([ 5, 10, 15])

In [ ]:
u = np.array([1,2,3])
l = np.array([4,5,6])
q = np.concatenate([u,l])
q

array([1, 2, 3, 4, 5, 6])

In [ ]:
b = np.random.randint(10,61,(7,6))
b

array([[58, 58, 19, 24, 34, 34],
       [27, 41, 11, 49, 57, 18],
       [49, 59, 13, 60, 45, 16],
       [38, 52, 23, 41, 44, 41],
       [30, 36, 58, 52, 14, 34],
       [27, 26, 43, 55, 59, 39],
       [36, 29, 53, 23, 40, 44]])

In [ ]:
#b[:,1:2],b[:,3:4],b[:,5:6] # 1
print(b[:,1:2])

[[58]
 [41]
 [59]
 [52]
 [36]
 [26]
 [29]]

In [ ]:
b[3,:] # 2

array([38, 52, 23, 41, 44, 41])

In [ ]:
b[4:,3::] # 3

array([[52, 14, 34],
       [55, 59, 39],
       [23, 40, 44]])

In [ ]:
b[4:,0] # 4

array([30, 27, 36])

In [ ]:
b[5,1:3:] # 5

array([26, 43])

------------------------------------------------

HOCANIN VERİCEĞİ OLAN ÖRNEK SINAV BENZERİ SORULAR

In [ ]:
a = np.random.randint(10,96,(3,5)) # 1
a

array([[54, 32, 88, 51, 36],
       [46, 21, 62, 91, 93],
       [13, 60, 29, 63, 47]])

In [ ]:
b = np.random.randint(10,101,(3,5)) # 2
b

array([[48, 45, 70, 70, 66],
       [99, 90, 83, 71, 51],
       [76, 45, 43, 58, 56]])

In [ ]:
print(b.size) # 3

15

In [ ]:
print(b[:,1:2]," ",b[:,3:4]) # 4

[[45]
 [90]
 [45]]   [[70]
 [71]
 [58]]

In [ ]:
print(b[b>50]) # 5

[70 70 66 99 90 83 71 51 76 58 56]

In [ ]:
c = np.concatenate([a,b]) # 6
c

array([[54, 32, 88, 51, 36],
       [46, 21, 62, 91, 93],
       [13, 60, 29, 63, 47],
       [48, 45, 70, 70, 66],
       [99, 90, 83, 71, 51],
       [76, 45, 43, 58, 56]])

In [ ]:
cDuzgun = np.sort(c) # 7
cDuzgun

array([[32, 36, 51, 54, 88],
       [21, 46, 62, 91, 93],
       [13, 29, 47, 60, 63],
       [45, 48, 66, 70, 70],
       [51, 71, 83, 90, 99],
       [43, 45, 56, 58, 76]])

In [ ]:
cEkli = 10+cDuzgun # 8
cEkli

array([[ 42,  46,  61,  64,  98],
       [ 31,  56,  72, 101, 103],
       [ 23,  39,  57,  70,  73],
       [ 55,  58,  76,  80,  80],
       [ 61,  81,  93, 100, 109],
       [ 53,  55,  66,  68,  86]])

In [ ]:
# 9
print(cEkli.min()) # En küçük
print(cEkli.max()) # En Büyük

23
109

In [ ]:
print(cEkli.sum()) # 10

2057

PANDAS

In [8]:
import pandas as pd

In [10]:
ds = pd.read_csv("Cheapestelectriccars-EVDatabase.csv")
ds

,Name,Subtitle,Acceleration,TopSpeed,Range,Efficiency,FastChargeSpeed,Drive,NumberofSeats,PriceinGermany,PriceinUK
0,Opel Ampera-e,Battery Electric Vehicle | 58 kWh,7.3 sec,150 km/h,335 km,173 Wh/km,210 km/h,Front Wheel Drive,5,"€42,990",NaN
1,Renault Kangoo Maxi ZE 33,Battery Electric Vehicle | 31 kWh,22.4 sec,130 km/h,160 km,194 Wh/km,-,Front Wheel Drive,5,NaN,"£31,680"
2,Nissan Leaf,Battery Electric Vehicle | 36 kWh,7.9 sec,144 km/h,220 km,164 Wh/km,230 km/h,Front Wheel Drive,5,"€29,990","£25,995"
3,Audi e-tron Sportback 55 quattro,Battery Electric Vehicle | 86.5 kWh,5.7 sec,200 km/h,375 km,231 Wh/km,600 km/h,All Wheel Drive,5,NaN,"£79,900"
4,Porsche Taycan Turbo S,Battery Electric Vehicle | 83.7 kWh,2.8 sec,260 km/h,390 km,215 Wh/km,860 km/h,All Wheel Drive,4,"€186,336","£138,830"
...,...,...,...,...,...,...,...,...,...,...,...
175,MG Marvel R,Battery Electric Vehicle | 65 kWh,7.9 sec,200 km/h,340 km,191 Wh/km,390 km/h,Rear Wheel Drive,5,"€40,000",NaN
176,Tesla Model 3 Long Range Dual Motor,Battery Electric Vehicle | 76 kWh,4.4 sec,233 km/h,490 km,155 Wh/km,820 km/h,All Wheel Drive,5,"€53,560",NaN
177,MG MG5 EV Long Range,Battery Electric Vehicle | 57 kWh,7.7 sec,185 km/h,340 km,168 Wh/km,340 km/h,Front Wheel Drive,5,NaN,"£26,495"
178,Audi Q4 e-tron 45 quattro,Battery Electric Vehicle | 76.6 kWh,6.9 sec,180 km/h,385 km,199 Wh/km,470 km/h,All Wheel Drive,5,"€50,900",NaN
179,Audi Q4 Sportback e-tron 40,Battery Electric Vehicle | 76.6 kWh,8.5 sec,160 km/h,425 km,180 Wh/km,520 km/h,Rear Wheel Drive,5,"€49,500",NaN

In [4]:
ds.tail()

,Name,Subtitle,Acceleration,TopSpeed,Range,Efficiency,FastChargeSpeed,Drive,NumberofSeats,PriceinGermany,PriceinUK
175,MG Marvel R,Battery Electric Vehicle | 65 kWh,7.9 sec,200 km/h,340 km,191 Wh/km,390 km/h,Rear Wheel Drive,5,"€40,000",NaN
176,Tesla Model 3 Long Range Dual Motor,Battery Electric Vehicle | 76 kWh,4.4 sec,233 km/h,490 km,155 Wh/km,820 km/h,All Wheel Drive,5,"€53,560",NaN
177,MG MG5 EV Long Range,Battery Electric Vehicle | 57 kWh,7.7 sec,185 km/h,340 km,168 Wh/km,340 km/h,Front Wheel Drive,5,NaN,"£26,495"
178,Audi Q4 e-tron 45 quattro,Battery Electric Vehicle | 76.6 kWh,6.9 sec,180 km/h,385 km,199 Wh/km,470 km/h,All Wheel Drive,5,"€50,900",NaN
179,Audi Q4 Sportback e-tron 40,Battery Electric Vehicle | 76.6 kWh,8.5 sec,160 km/h,425 km,180 Wh/km,520 km/h,Rear Wheel Drive,5,"€49,500",NaN

In [6]:
ds.head()

,Name,Subtitle,Acceleration,TopSpeed,Range,Efficiency,FastChargeSpeed,Drive,NumberofSeats,PriceinGermany,PriceinUK
0,Opel Ampera-e,Battery Electric Vehicle | 58 kWh,7.3 sec,150 km/h,335 km,173 Wh/km,210 km/h,Front Wheel Drive,5,"€42,990",NaN
1,Renault Kangoo Maxi ZE 33,Battery Electric Vehicle | 31 kWh,22.4 sec,130 km/h,160 km,194 Wh/km,-,Front Wheel Drive,5,NaN,"£31,680"
2,Nissan Leaf,Battery Electric Vehicle | 36 kWh,7.9 sec,144 km/h,220 km,164 Wh/km,230 km/h,Front Wheel Drive,5,"€29,990","£25,995"
3,Audi e-tron Sportback 55 quattro,Battery Electric Vehicle | 86.5 kWh,5.7 sec,200 km/h,375 km,231 Wh/km,600 km/h,All Wheel Drive,5,NaN,"£79,900"
4,Porsche Taycan Turbo S,Battery Electric Vehicle | 83.7 kWh,2.8 sec,260 km/h,390 km,215 Wh/km,860 km/h,All Wheel Drive,4,"€186,336","£138,830"

In [7]:
ds.head(15)

,Name,Subtitle,Acceleration,TopSpeed,Range,Efficiency,FastChargeSpeed,Drive,NumberofSeats,PriceinGermany,PriceinUK
0,Opel Ampera-e,Battery Electric Vehicle | 58 kWh,7.3 sec,150 km/h,335 km,173 Wh/km,210 km/h,Front Wheel Drive,5,"€42,990",NaN
1,Renault Kangoo Maxi ZE 33,Battery Electric Vehicle | 31 kWh,22.4 sec,130 km/h,160 km,194 Wh/km,-,Front Wheel Drive,5,NaN,"£31,680"
2,Nissan Leaf,Battery Electric Vehicle | 36 kWh,7.9 sec,144 km/h,220 km,164 Wh/km,230 km/h,Front Wheel Drive,5,"€29,990","£25,995"
3,Audi e-tron Sportback 55 quattro,Battery Electric Vehicle | 86.5 kWh,5.7 sec,200 km/h,375 km,231 Wh/km,600 km/h,All Wheel Drive,5,NaN,"£79,900"
4,Porsche Taycan Turbo S,Battery Electric Vehicle | 83.7 kWh,2.8 sec,260 km/h,390 km,215 Wh/km,860 km/h,All Wheel Drive,4,"€186,336","£138,830"
5,Nissan e-NV200 Evalia,Battery Electric Vehicle | 36 kWh,14.0 sec,123 km/h,165 km,218 Wh/km,170 km/h,Front Wheel Drive,7,"€43,433","£30,255"
6,Volkswagen ID.3 Pure Performance,Battery Electric Vehicle | 45 kWh,8.9 sec,160 km/h,275 km,164 Wh/km,260 km/h,Rear Wheel Drive,5,"€31,960","£27,120"
7,BMW iX3,Battery Electric Vehicle | 74 kWh,6.8 sec,180 km/h,385 km,192 Wh/km,520 km/h,Rear Wheel Drive,5,"€66,300","£58,850"
8,Nissan Leaf e+,Battery Electric Vehicle | 56 kWh,7.3 sec,157 km/h,325 km,172 Wh/km,390 km/h,Front Wheel Drive,5,"€38,350","£30,445"
9,BMW i3 120 Ah,Battery Electric Vehicle | 37.9 kWh,7.3 sec,150 km/h,235 km,161 Wh/km,270 km/h,Rear Wheel Drive,4,"€39,000","£31,305"
10,Mercedes EQA 250,Battery Electric Vehicle | 66.5 kWh,8.9 sec,160 km/h,355 km,187 Wh/km,420 km/h,Front Wheel Drive,5,"€47,541","£43,495"
11,DS 3 Crossback E-Tense,Battery Electric Vehicle | 45 kWh,8.7 sec,150 km/h,250 km,180 Wh/km,330 km/h,Front Wheel Drive,5,"€30,040","£31,500"
12,BMW i3s 120 Ah,Battery Electric Vehicle | 37.9 kWh,6.9 sec,160 km/h,230 km,165 Wh/km,260 km/h,Rear Wheel Drive,4,"€42,600","£32,305"
13,Sono Sion,Battery Electric Vehicle | 47 kWh,9.0 sec,140 km/h,260 km,181 Wh/km,310 km/h,Front Wheel Drive,5,"€25,500",NaN
14,Audi e-tron GT RS,Battery Electric Vehicle | 85 kWh,3.3 sec,250 km/h,405 km,210 Wh/km,810 km/h,All Wheel Drive,4,"€138,200","£110,950"